## NumPy Basics

NumPy = Python library for numerical computing
              - Used for working with arrays

* Numpy is written on c. So c is faster execution than python.
* NumPy stores data in one block. So it is faster than python. Because of the Continuous memory.
* Numpy haven't loops.

Import NumPy

In [2]:
import numpy as np 

Create Arrays

In [3]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [10]:
b = np.array([[1, 2], [3, 4]])
print(b)

[[1 2]
 [3 4]]


Check Shape

In [ ]:
print(a.shape)  # Shape of array a (4,)  , represent 1D array
print(b.shape)  # Shape of array b (2, 2)  2 row 2 col

(4,)
(2, 2)


Operations witth array

In [ ]:
print(a + 2)
print(a * 2)

[3 4 5 6]
[2 4 6 8]


Create Zeros and Ones

In [ ]:
print(np.zeros((2,2)))    # 2*2 matrix filled 0
print(np.ones((3,3)))     # 3*3 matrix filled 1

[[0. 0.]
 [0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


🔹Practice Task

In [ ]:
c = np.array([10, 20, 30, 40, 50])  # Create array

In [ ]:
print(c * 3)    # Multiply all values by 3

[ 30  60  90 120 150]


In [27]:
print(np.sum(c))    # Find Sum

150


In [28]:
print(np.mean(c))   # Find Mean

30.0


In [32]:
matrix = np.array([[1,2,3],[4,5,6]])

In [33]:
print(matrix.shape)

(2, 3)


In [34]:
print(matrix * 2)

[[ 2  4  6]
 [ 8 10 12]]


* Sum → integer
* Mean → always float