## NumPy Indexing & Operations

### Indexing (Access Elements)

* Indexing - Access specific element in a list/array.
* Slicing - Access subset of elements.

* (*) Element wise multipliation
* np.dot() - Matrix multiplication

In [6]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])

In [8]:
print(arr[0])   # 10
print(arr[-1])  # 50 (Negative indexing)

10
50


In [12]:
matrix = np.array([[1, 2, 3],
                   [4, 5, 6]])  # 2D array

In [13]:
print(matrix[0, 0])  # 1
print(matrix[1, 2])  # 6

1
6


### Slicing

* 1D slicing

In [ ]:
print(arr[1:4])   # [20 30 40] Between 1 and 4
print(arr[:3])    # [10 20 30] <3
print(arr[::2])   # [10 30 50] Skip 1 by 1

[20 30 40]
[10 20 30]
[10 30 50]


* 2D slicing

In [19]:
print(matrix[:, 0])   # first column
print(matrix[0, :])   # first row

[1 4]
[1 2 3]


### Modify Values

In [20]:
arr[0] = 100
print(arr)

[100  20  30  40  50]


### Matrix Operations

In [21]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

In [22]:
print(a + b)
print(a * b)

[5 7 9]
[ 4 10 18]


In [23]:
m1 = np.array([[1, 2],
               [3, 4]])

m2 = np.array([[5, 6],
               [7, 8]])

In [24]:
print(m1 + m2)
print(m1 * m2)  # element-wise

[[ 6  8]
 [10 12]]
[[ 5 12]
 [21 32]]


In [25]:
print(np.dot(m1, m2))

[[19 22]
 [43 50]]


🔹Practice Task

In [26]:
arr = [5, 10, 15, 20, 25]

In [30]:
print(arr[:3])  # First 3 elements
print(arr[-2:]) # Last 2 elements

[5, 10, 15]
[20, 25]


In [44]:
matrix = [[10,20,30],
          [40,50,60]]

In [ ]:
print(matrix[1])    # Second row

[40, 50, 60]


In [ ]:
print([row[2] for row in matrix])   # Third column

[30, 60]


In [53]:
matrix = [[1,2,3],
          [4,5,6],
          [7,8,9]]

In [ ]:
print(matrix[1]) # Extract middle row

[4, 5, 6]


In [ ]:
print([row[2] for row in matrix]) # Extract last column

[3, 6, 9]


In [ ]:
print([[element * 3 for element in row] for row in matrix]) # Multiply entire matrix by 3

[[3, 6, 9], [12, 15, 18], [21, 24, 27]]


Slicing used in:
* * Training data
* * Testing data