## Broadcasting + Reshaping

* Broadcasting = NumPy automatically matches shapes

In [2]:
import numpy as np

arr = np.array([1, 2, 3])
print(arr + 5)              # Adds 5 to every element without loop

[6 7 8]


In [4]:
a = np.array([1, 2, 3])
b = np.array([10, 20, 30])

print(a + b)           # Broadcasting with arrays

[11 22 33]


In [5]:
matrix = np.array([[1,2,3],
                   [4,5,6]])

row = np.array([10, 20, 30])

print(matrix + row)         

# Different shapes
# row stretched to [10 20 30]
#                  [10 20 30]

[[11 22 33]
 [14 25 36]]


Reshaping Arrays

In [9]:
arr = np.array([1,2,3,4,5,6])
print(arr.shape)        # Original shape

(6,)


In [10]:
print(arr.reshape(2,3))  # array.reshape(rows, columns)

[[1 2 3]
 [4 5 6]]


* No. of element must be same,

    Original elements = new rows * new columns
    *   6 = 2 * 3
    *   6 = 3 * 2

In [11]:
print(arr.reshape(3,2))

[[1 2]
 [3 4]
 [5 6]]


Flatten

In [15]:
matrix = np.array([[1,2,3],
                   [4,5,6]])

print(matrix.flatten())     # .flatten() converts any n-dimensional array into a 1D array

[1 2 3 4 5 6]


* reshape() → changes shape but keeps rows & columns
* flatten() → makes everything 1D

🔹Practice Task

In [18]:
arr = np.array([2,4,6])
print(arr + 10)

[12 14 16]


In [19]:
arr = np.array([1,2,3,4])
print(arr.reshape(2,2))



[[1 2]
 [3 4]]


In [ ]:
matrix = np.array([[1,2],
                   [3,4]])  

print(matrix.flatten())

[1 2 3 4]


In [ ]:
arr = np.array([1,2,3,4,5,6,7,8])
print(arr.reshape(2,4))

[[1 2 3 4]
 [5 6 7 8]]


In [30]:
a= arr.reshape(2,4)
b = np.array([10,20,30,40])
print(a + b)

[[11 22 33 44]
 [15 26 37 48]]


Broadcasting in NumPy is:

Automatically expanding arrays of different shapes so you can perform element-wise operations without writing loops.